# Generated by Django 3.1.1 on 2020-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('jwt_auth', '0002_auto_20200913_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workouts',
            field=models.ManyToManyField(related_name='users', to='workouts.Workout'),
        ),
    ]
