# Generated by Django 3.1.1 on 2020-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body_part', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.TextField()),
                ('video', models.TextField()),
            ],
        ),
    ]
