# Generated by Django 3.1.1 on 2020-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='exercises.Exercise'),
        ),
    ]
